Make ssh magic wrapper able to handle more than just /usr/bin

diff --git a/bin/ssh b/bin/ssh
--- a/bin/ssh
+++ b/bin/ssh
@@ -1,5 +1,14 @@
 #!/usr/bin/env bash
 
+# TODO: automatically pull $stems from $PATH, removing the directory
+# of this script if included.
+stems=(/usr/bin /usr/local/bin)
 [[ -z `ssh-add -l | grep $HOME/.ssh/id_rsa` ]] && ssh-add
 name=$(basename $0)
-exec /usr/bin/$name "$@"
+for stem in ${stems[@]}; do
+	if [ -x $stem/$name ]; then
+		exec $stem/$name "$@"
+	fi
+done
+echo "Could not find an executable for $name in ${stems[@]}."
+exit 1
